[2025-02-18T18:30:48.475+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:30:48.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:30:48.478+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:30:48.477+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:30:50.684+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:30:50.676+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:30:50.687+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:30:50.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 2.234 seconds
[2025-02-18T18:31:21.557+0000] {processor.py:157} INFO - Started process (PID=177) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:31:21.558+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:31:21.559+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:31:21.559+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:31:22.253+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:31:22.242+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:31:22.257+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:31:22.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.757 seconds
[2025-02-18T18:31:52.797+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:31:52.798+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:31:52.799+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:31:52.799+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:31:53.572+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:31:53.563+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:31:53.575+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:31:53.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.804 seconds
[2025-02-18T18:32:24.304+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:32:24.307+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:32:24.312+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:32:24.311+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:32:25.074+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:32:25.064+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:32:25.078+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:32:25.103+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.809 seconds
[2025-02-18T18:32:55.520+0000] {processor.py:157} INFO - Started process (PID=195) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:32:55.521+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:32:55.522+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:32:55.522+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:32:56.208+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:32:56.195+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:32:56.212+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:32:56.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.720 seconds
[2025-02-18T18:33:26.997+0000] {processor.py:157} INFO - Started process (PID=201) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:33:26.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:33:26.999+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:33:26.999+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:33:27.664+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:33:27.655+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:33:27.667+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:33:27.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.700 seconds
[2025-02-18T18:33:58.151+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:33:58.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:33:58.153+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:33:58.153+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:33:58.879+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:33:58.865+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:33:58.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:33:58.908+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.763 seconds
[2025-02-18T18:34:29.575+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:34:29.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:34:29.577+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:34:29.577+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:34:30.253+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:34:30.240+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:34:30.258+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:34:30.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.708 seconds
[2025-02-18T18:35:00.857+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:35:00.860+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:35:00.863+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:35:00.863+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:35:01.703+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:35:01.692+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:35:01.707+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:35:01.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.896 seconds
[2025-02-18T18:35:32.259+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:35:32.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:35:32.262+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:35:32.262+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:35:32.919+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:35:32.906+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:35:32.926+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:35:32.950+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.696 seconds
[2025-02-18T18:36:03.717+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:36:03.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:36:03.720+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:36:03.719+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:36:04.456+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:36:04.444+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:36:04.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:36:04.484+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.773 seconds
[2025-02-18T18:36:34.839+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:36:34.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:36:34.841+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:36:34.841+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:36:35.477+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:36:35.466+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:36:35.480+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:36:35.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.665 seconds
[2025-02-18T18:37:06.442+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:37:06.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:37:06.444+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:37:06.444+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:37:07.053+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:37:07.042+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:37:07.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:37:07.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.638 seconds
[2025-02-18T18:37:37.417+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:37:37.418+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:37:37.420+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:37:37.419+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:37:38.110+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:37:38.095+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:37:38.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:37:38.163+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.752 seconds
[2025-02-18T18:38:09.001+0000] {processor.py:157} INFO - Started process (PID=261) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:38:09.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:38:09.004+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:38:09.004+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:38:09.701+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:38:09.692+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:38:09.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:38:09.751+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.755 seconds
[2025-02-18T18:38:40.087+0000] {processor.py:157} INFO - Started process (PID=267) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:38:40.088+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:38:40.089+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:38:40.089+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:38:40.807+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:38:40.794+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:38:40.811+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:38:40.829+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.747 seconds
[2025-02-18T18:39:11.782+0000] {processor.py:157} INFO - Started process (PID=273) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:39:11.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:39:11.784+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:39:11.784+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:39:12.441+0000] {logging_mixin.py:154} INFO - [2025-02-18T18:39:12.433+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:39:12.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:39:12.468+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.692 seconds
[2025-02-18T18:52:41.863+0000] {processor.py:186} INFO - Started process (PID=184) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:52:41.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:52:41.866+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:52:41.866+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:52:43.625+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:52:43.616+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:52:43.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:52:43.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.795 seconds
[2025-02-18T18:53:13.872+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:53:13.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:53:13.877+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:13.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:53:14.695+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:14.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline.py", line 16, in <module>
    from src.etl.extract_mongodb import get_validated_mongodb_data
  File "/opt/airflow/src/etl/extract_mongodb.py", line 4, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-02-18T18:53:14.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:53:14.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 0.988 seconds
[2025-02-18T18:53:45.124+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:53:45.125+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:53:45.127+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:45.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:53:46.900+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:53:47.295+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.294+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:etl_pipeline_with_tasks
[2025-02-18T18:53:47.309+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.309+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:etl_pipeline_with_tasks
[2025-02-18T18:53:47.318+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.318+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:etl_pipeline_with_tasks
[2025-02-18T18:53:47.329+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.328+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:etl_pipeline_with_tasks
[2025-02-18T18:53:47.340+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.340+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:etl_pipeline_with_tasks
[2025-02-18T18:53:47.356+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.355+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:etl_pipeline_with_tasks
[2025-02-18T18:53:47.369+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.369+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:etl_pipeline_with_tasks
[2025-02-18T18:53:47.371+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.370+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:53:47.407+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.406+0000] {dag.py:3262} INFO - Creating ORM DAG for etl_pipeline_with_tasks
[2025-02-18T18:53:47.428+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:53:47.428+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-17 00:00:00+00:00, run_after=2025-02-18 00:00:00+00:00
[2025-02-18T18:53:47.468+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 2.358 seconds
[2025-02-18T18:54:17.842+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:54:17.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:54:17.845+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:54:17.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:54:20.525+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:54:20.570+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:54:20.569+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:54:20.606+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:54:20.606+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-17 00:00:00+00:00, run_after=2025-02-18 00:00:00+00:00
[2025-02-18T18:54:20.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.939 seconds
[2025-02-18T18:54:51.628+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:54:51.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:54:51.631+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:54:51.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:54:52.879+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:54:52.924+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:54:52.924+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:54:52.971+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:54:52.971+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-17 00:00:00+00:00, run_after=2025-02-18 00:00:00+00:00
[2025-02-18T18:54:53.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.404 seconds
[2025-02-18T18:55:23.226+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:55:23.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:55:23.238+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:55:23.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:55:24.375+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:55:24.404+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:55:24.404+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:55:24.433+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:55:24.433+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:55:24.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.252 seconds
[2025-02-18T18:55:54.735+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:55:54.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:55:54.740+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:55:54.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:55:56.159+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:55:56.198+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:55:56.198+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:55:56.232+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:55:56.232+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:55:56.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.571 seconds
[2025-02-18T18:56:26.667+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:56:26.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:56:26.671+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:56:26.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:56:28.091+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:56:28.131+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:56:28.129+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:56:28.164+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:56:28.163+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:56:28.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.535 seconds
[2025-02-18T18:56:58.483+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:56:58.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:56:58.487+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:56:58.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:56:59.639+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:56:59.667+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:56:59.666+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:56:59.696+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:56:59.695+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:56:59.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.250 seconds
[2025-02-18T18:57:30.030+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:57:30.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:57:30.034+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:57:30.034+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:57:31.330+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:57:31.359+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:57:31.359+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:57:31.390+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:57:31.389+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:57:31.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.400 seconds
[2025-02-18T18:58:01.832+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:58:01.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:58:01.837+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:58:01.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:58:03.076+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:58:03.103+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:58:03.102+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:58:03.131+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:58:03.130+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:58:03.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.385 seconds
[2025-02-18T18:58:33.524+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:58:33.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:58:33.529+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:58:33.528+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:58:34.909+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:58:34.944+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:58:34.944+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:58:34.976+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:58:34.976+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:58:35.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.495 seconds
[2025-02-18T18:59:05.334+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:59:05.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl_pipeline.py for tasks to queue
[2025-02-18T18:59:05.339+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:59:05.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:59:06.833+0000] {processor.py:925} INFO - DAG(s) 'etl_pipeline_with_tasks' retrieved from /opt/airflow/dags/etl_pipeline.py
[2025-02-18T18:59:06.875+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:59:06.874+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-02-18T18:59:06.905+0000] {logging_mixin.py:190} INFO - [2025-02-18T18:59:06.905+0000] {dag.py:4180} INFO - Setting next_dagrun for etl_pipeline_with_tasks to 2025-02-18 00:00:00+00:00, run_after=2025-02-19 00:00:00+00:00
[2025-02-18T18:59:06.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl_pipeline.py took 1.622 seconds
