[2025-02-20T05:47:35.573+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T05:47:35.598+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_with_tasks.extract_mongodb manual__2025-02-20T05:47:33.251853+00:00 [queued]>
[2025-02-20T05:47:35.613+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_with_tasks.extract_mongodb manual__2025-02-20T05:47:33.251853+00:00 [queued]>
[2025-02-20T05:47:35.615+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-20T05:47:35.638+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): extract_mongodb> on 2025-02-20 05:47:33.251853+00:00
[2025-02-20T05:47:35.647+0000] {standard_task_runner.py:72} INFO - Started process 290 to run task
[2025-02-20T05:47:35.653+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_with_tasks', 'extract_mongodb', 'manual__2025-02-20T05:47:33.251853+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpjr5r517v']
[2025-02-20T05:47:35.660+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask extract_mongodb
[2025-02-20T05:47:35.736+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_with_tasks.extract_mongodb manual__2025-02-20T05:47:33.251853+00:00 [running]> on host ae3f561e8b28
[2025-02-20T05:47:35.877+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_with_tasks' AIRFLOW_CTX_TASK_ID='extract_mongodb' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T05:47:33.251853+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T05:47:33.251853+00:00'
[2025-02-20T05:47:35.880+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T05:47:35.885+0000] {extract_mongodb.py:38} INFO - Connecting MongoDB server
[2025-02-20T05:47:36.364+0000] {extract_mongodb.py:43} INFO - MongoDB server connected
[2025-02-20T05:47:36.366+0000] {extract_mongodb.py:44} INFO - =================================================================
[2025-02-20T05:47:36.369+0000] {extract_mongodb.py:55} INFO - Loading data from mongodb
[2025-02-20T05:47:38.935+0000] {extract_mongodb.py:61} INFO - Converting fetched data to Dataframe
[2025-02-20T05:47:39.018+0000] {extract_mongodb.py:66} INFO - Drop unnecessary column '_id'
[2025-02-20T05:47:39.020+0000] {extract_mongodb.py:68} INFO - Loaded 17853 records from mongodb database and converted into pandas DataFrame
[2025-02-20T05:47:39.052+0000] {extract_mongodb.py:85} INFO - MongoDB Data Validated Successfully
[2025-02-20T05:47:39.057+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 48, in extract_mongodb
    mongo_df = get_validated_mongodb_data()
  File "/opt/airflow/src/etl/extract_mongodb.py", line 87, in get_validated_mongodb_data
    df.to_csv(mongodb_data_save_path, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'Processed_Data'
[2025-02-20T05:47:39.079+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline_with_tasks, task_id=extract_mongodb, run_id=manual__2025-02-20T05:47:33.251853+00:00, execution_date=20250220T054733, start_date=20250220T054735, end_date=20250220T054739
[2025-02-20T05:47:39.148+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T05:47:39.150+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 44 for task extract_mongodb (Cannot save file into a non-existent directory: 'Processed_Data'; 290)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 48, in extract_mongodb
    mongo_df = get_validated_mongodb_data()
  File "/opt/airflow/src/etl/extract_mongodb.py", line 87, in get_validated_mongodb_data
    df.to_csv(mongodb_data_save_path, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'Processed_Data'
[2025-02-20T05:47:39.200+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-20T05:47:39.233+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T05:47:39.237+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
